"""
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
    Input:
        s = "abcd"
        t = "abcde"
    Output:
        e
Explanation:
    'e' is the letter that was added.
"""


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        l = list(t)
        for i in s:
            if i in t:
                l.remove(i)
        return l[0]
# Runtime: 48 ms, faster than 13.36% (2020/02/24)
# Memory Usage: 12.8 MB, less than 100.00% (2020/02/24)


class Solution_2:
    def findTheDifference(self, s: str, t: str) -> str:
        for i in t:
            if i not in s:
                return i
            else:
                if t.count(i) != s.count(i):
                    return i
# Runtime: 32 ms, faster than 69.08% (2020/02/24)
# Memory Usage: 12.7 MB, less than 100.00% (2020/02/24)


